// <auto-generated />
using FutureAPIv1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FutureAPIv1.Migrations
{
    [DbContext(typeof(FutureAPIv1Context))]
    [Migration("20200130200430_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FutureAPIv1.PolygonPoints", b =>
                {
                    b.Property<int>("PolyPointID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("lat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("lng")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("objectID")
                        .HasColumnType("int");

                    b.HasKey("PolyPointID");

                    b.ToTable("PolygonPoints");
                });

            modelBuilder.Entity("FutureAPIv1.Polygons", b =>
                {
                    b.Property<int>("objectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Post_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShapeArea")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShapeLen")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("objectID");

                    b.ToTable("Polygons");
                });
#pragma warning restore 612, 618
        }
    }
}
